// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizza_Management_System_DAL.Context;

#nullable disable

namespace Pizza_Management_System_API.Migrations
{
    [DbContext(typeof(PizzaContext))]
    partial class PizzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaTopping", b =>
                {
                    b.Property<Guid>("PizzasID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToppingsID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PizzasID", "ToppingsID");

                    b.HasIndex("ToppingsID");

                    b.ToTable("PizzaTopping");
                });

            modelBuilder.Entity("Pizza_Management_System_DAL.Entities.Pizza", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pizza_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SauceID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("SauceID");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("Pizza_Management_System_DAL.Entities.Sauce", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_vegan")
                        .HasColumnType("bit");

                    b.Property<string>("Sauce_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sauces");
                });

            modelBuilder.Entity("Pizza_Management_System_DAL.Entities.Topping", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Topping_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Toppings");
                });

            modelBuilder.Entity("PizzaTopping", b =>
                {
                    b.HasOne("Pizza_Management_System_DAL.Entities.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pizza_Management_System_DAL.Entities.Topping", null)
                        .WithMany()
                        .HasForeignKey("ToppingsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizza_Management_System_DAL.Entities.Pizza", b =>
                {
                    b.HasOne("Pizza_Management_System_DAL.Entities.Sauce", "Sauce")
                        .WithMany()
                        .HasForeignKey("SauceID");

                    b.Navigation("Sauce");
                });
#pragma warning restore 612, 618
        }
    }
}
